---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: deploy-a-vm-win-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: deploy-a-vm-win
  extra_vars: 